# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('link', models.URLField(default='')),
                ('order', models.SmallIntegerField(default=0)),
                ('blank', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
