# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
        ('tagcloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blocks.Block'),
        ),
    ]
