# Generated by Django 2.2.2 on 2019-07-15 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_mediafile_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20190626_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(blank=True, max_length=40, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('title', models.TextField(max_length=255)),
                ('description', models.CharField(default='', max_length=512)),
                ('keywords', models.CharField(default='', max_length=512)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Hidden'), (2, 'Public')], default=0)),
                ('sticked', models.BooleanField(default=False)),
                ('comments_enabled', models.BooleanField(default=True)),
                ('comments_moderated', models.BooleanField(default=True)),
                ('do_ping', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('teaser', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(null=True, to='blog.Category')),
                ('social_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.MediaFile')),
                ('tags', models.ManyToManyField(null=True, to='blog.Tag')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created'],
            },
        ),
    ]
