# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_image',
            field=models.BooleanField(default=True, verbose_name='Is image'),
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
