# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 10:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_media_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
