# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
