"""empty message

Revision ID: 70731151f57a
Revises: 02378ef10974
Create Date: 2016-02-04 11:37:36.534655

"""

# revision identifiers, used by Alembic.
revision = '70731151f57a'
down_revision = '02378ef10974'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('slug', sa.String(length=60), nullable=True),
    sa.Column('categoryname', sa.String(length=60), nullable=True),
    sa.Column('order', sa.SmallInteger(), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_blog_category_categoryname'), 'blog_category', ['categoryname'], unique=False)
    op.create_index(op.f('ix_blog_category_slug'), 'blog_category', ['slug'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_category_slug'), table_name='blog_category')
    op.drop_index(op.f('ix_blog_category_categoryname'), table_name='blog_category')
    op.drop_table('blog_category')
    ### end Alembic commands ###
