"""empty message

Revision ID: 79cd32938c2e
Revises: c80f7ea2e74a
Create Date: 2016-02-08 13:04:31.316488

"""

# revision identifiers, used by Alembic.
revision = '79cd32938c2e'
down_revision = 'c80f7ea2e74a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('keywords', sa.String(length=250), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.Column('published', sa.DateTime(), nullable=True),
    sa.Column('sticked', sa.Boolean(), nullable=True),
    sa.Column('ping', sa.Boolean(), nullable=True),
    sa.Column('comments_enabled', sa.Boolean(), nullable=True),
    sa.Column('comments_moderated', sa.Boolean(), nullable=True),
    sa.Column('template', sa.SmallInteger(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('teaser', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('prev', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('post_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_blog_post_slug'), 'blog_post', ['slug'], unique=True)
    op.create_index(op.f('ix_blog_post_title'), 'blog_post', ['title'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_post_title'), table_name='blog_post')
    op.drop_index(op.f('ix_blog_post_slug'), table_name='blog_post')
    op.drop_table('blog_post')
    ### end Alembic commands ###
