"""empty message

Revision ID: c80f7ea2e74a
Revises: 70731151f57a
Create Date: 2016-02-07 01:52:59.115506

"""

# revision identifiers, used by Alembic.
revision = 'c80f7ea2e74a'
down_revision = '70731151f57a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links_mylink',
    sa.Column('mylink_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('slug', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('blank', sa.Boolean(), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('mylink_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_links_mylink_link'), 'links_mylink', ['link'], unique=False)
    op.create_index(op.f('ix_links_mylink_name'), 'links_mylink', ['name'], unique=False)
    op.create_index(op.f('ix_links_mylink_slug'), 'links_mylink', ['slug'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_mylink_slug'), table_name='links_mylink')
    op.drop_index(op.f('ix_links_mylink_name'), table_name='links_mylink')
    op.drop_index(op.f('ix_links_mylink_link'), table_name='links_mylink')
    op.drop_table('links_mylink')
    ### end Alembic commands ###
