"""empty message

Revision ID: c77adb22f953
Revises: 79cd32938c2e
Create Date: 2016-02-08 13:27:03.701153

"""

# revision identifiers, used by Alembic.
revision = 'c77adb22f953'
down_revision = '79cd32938c2e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_tags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['blog_post.post_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['blog_tag.tag_id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_tags')
    ### end Alembic commands ###
