# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20151224_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylinks',
            name='new_window',
            field=models.BooleanField(default=True),
        ),
    ]
