# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_mylinks_new_window'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='MyLink',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('slug', models.SlugField(default='', max_length=255)),
        #         ('name', models.CharField(default='', max_length=255)),
        #         ('link', models.URLField(default='')),
        #         ('order', models.SmallIntegerField(default=0)),
        #         ('new_window', models.BooleanField(default=True)),
        #         ('deleted', models.BooleanField(default=False)),
        #    ],
        #     options={
        #         'ordering': ['order', 'name'],
        #     },
        # ),
        migrations.RenameModel(
            old_name='MyLinks',
            new_name='MyLink',
        ),
    ]
