# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20160215_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylink',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
    ]
