# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_mylink_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mylink',
            old_name='new_window',
            new_name='blank',
        ),
    ]
