# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 05:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 9, 5, 32, 46, 846629, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
