# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='content_prev',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='teaser',
            field=models.TextField(default=''),
        ),
    ]
