# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(default='', max_length=255)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('referer', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('browser_family', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('browser_version', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('os_family', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('os_version', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('device_family', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_tablet', models.BooleanField(default=False)),
                ('is_touch_capable', models.BooleanField(default=False)),
                ('is_pc', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
