# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 07:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('order', models.IntegerField(default=10)),
                ('deleted', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(default='')),
                ('username', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('allowed', models.BooleanField(default=True)),
                ('content', models.TextField(default='')),
                ('agent', models.CharField(default='', max_length=255)),
                ('ip', models.CharField(default='', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'verbose_name': 'Comment',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('title', models.TextField(max_length=255)),
                ('description', models.CharField(default='', max_length=512)),
                ('keywords', models.CharField(default='', max_length=512)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Hidden'), (2, 'Public')], default=0)),
                ('sticked', models.BooleanField(default=False)),
                ('comments_enabled', models.BooleanField(default=True)),
                ('comments_moderated', models.BooleanField(default=True)),
                ('do_ping', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('teaser', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('content_prev', models.TextField(default='')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='blog.Category')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'verbose_name': 'Post',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'verbose_name': 'Tag',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
