# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170315_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_prev',
        ),
    ]
