# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170426_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
