# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='slug',
        ),
        migrations.AddField(
            model_name='folder',
            name='uuid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
