# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 16:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0002_auto_20160224_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='media.Folder')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Files',
                'verbose_name': 'File',
            },
        ),
    ]
