# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 16:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 24, 16, 10, 40, 48599, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
