# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_folder_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='image',
            field=models.BooleanField(default=False),
        ),
    ]
