# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 05:34
from __future__ import unicode_literals

import apps.media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_auto_20160425_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='image',
            new_name='is_image',
        ),
        migrations.AddField(
            model_name='file',
            name='f',
            field=models.ImageField(null=True, upload_to=apps.media.models.File.upload_to),
        ),
    ]
