# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_remove_file_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uuid',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
