# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 07:56
from __future__ import unicode_literals

import apps.media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_auto_20160425_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='f',
            field=models.FileField(null=True, upload_to=apps.media.models.File.upload_to, verbose_name='File'),
        ),
    ]
