# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170315_1703'),
        ('toolbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('passed', models.BooleanField(default=False)),
                ('message', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PingServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
            options={
                'ordering': ['address'],
            },
        ),
        migrations.AddField(
            model_name='pingresult',
            name='pingserver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.PingServer'),
        ),
        migrations.AddField(
            model_name='pingresult',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
