POST_STATUS_DRAFT = 0
POST_STATUS_HIDDEN = 1
POST_STATUS_PUBLISHED = 2

POST_STATUS = {
    POST_STATUS_DRAFT: 'Draft',
    POST_STATUS_HIDDEN: 'Hidden',
    POST_STATUS_PUBLISHED: 'Published'
}

POST_TEMPLATE_TEXT = 1
POST_TEMPLATE_PICTURE = 2
POST_TEMPLATE_GALLERY = 3
POST_TEMPLATE_VIDEO = 4
POST_TEMPLATE_AUDIO = 5
POST_TEMPLATE_LINK = 6

POST_TEMPLATE = {
    POST_TEMPLATE_TEXT: 'Test',
    POST_TEMPLATE_PICTURE: 'Picture',
    POST_TEMPLATE_GALLERY: 'Gallery',
    POST_TEMPLATE_VIDEO: 'Video',
    POST_TEMPLATE_AUDIO: 'Audio',
    POST_TEMPLATE_LINK: 'Link'
}

SIZE_NAME = 60
SIZE_UUID = 36
SIZE_TITLE = 120
SIZE_META = 250
