# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 12:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import odyssey.photo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('order', models.IntegerField(default=10)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albumss',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(blank=True, max_length=40, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('title', models.TextField(max_length=255)),
                ('description', models.CharField(default='', max_length=512)),
                ('keywords', models.CharField(default='', max_length=512)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Hidden'), (2, 'Public')], default=0)),
                ('sticked', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=odyssey.photo.models.Photo.image_path, verbose_name='Image')),
                ('albums', models.ManyToManyField(blank=True, to='photo.Album')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='photo.Tag'),
        ),
    ]
