# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20170407_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
