# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160323_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='social_image',
            field=models.TextField(default='', max_length=255),
        ),
    ]
