# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='social_image',
        ),
    ]
