# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_auto_20160425_1356'),
        ('blog', '0009_remove_post_social_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.File'),
        ),
    ]
