# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
