# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import odyssey.photo.models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20170420_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('image', models.ImageField(default='', upload_to=odyssey.photo.models.Device.image_path, verbose_name='Image')),
                ('content', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Devices',
                'ordering': ['name'],
                'verbose_name': 'Device',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('show_in_menu', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Device types',
                'ordering': ['name'],
                'verbose_name': 'Device type',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.DeviceType'),
        ),
    ]
