# Generated by Django 2.2.2 on 2019-07-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_mediafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='uid',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
    ]
