# Generated by Django 2.2.5 on 2019-09-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
