# Generated by Django 2.2.5 on 2019-09-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_link_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='order',
            field=models.IntegerField(default=10),
        ),
    ]
